# Change these first
owner: bachmannschumacher
repo: upptime

assignees:
  - thomasrehm

sites:
  - name: Bachmann + Schumacher Website
    url: https://bachmannschumacher.com
  - name: SM Service
    url: http://smservice.de
  - name: 2rad circle
    url: https://2rad-circle.de
  - name: 2rad circle App
    url: https://app.2rad-circle.de

status-website:
#  cname: bachmannschumacher.github.io
  baseUrl: /upptime
  theme: dark
  robotsText: "User-agent: * \n Disallow: /"
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Bachmann + Schumacher Uptime 
  navbar:
    - title: Status
      href: /

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"


# See https://upptime.js.org/docs/configuration
